### ISSUE TITLE
Fails to build as dependency of Cuppa

### ISSUE THREAD

**Issue by maxice8** [DataDrake/cli-ng#1]
Trying to package `cuppa` for [Void Linux](https://github.com/void-linux/void-packages/pull/6409) and running into this error.

```
# github.com/DataDrake/cli-ng/translate
_build-cuppa-xbps/src/github.com/DataDrake/cli-ng/translate/en_US.go:29:10: cannot use enUS (type string) as type []byte in argument to po.Parse
```

[Full log](http://ix.io/1xex)

**Comment by DataDrake** [comment]
Oooh. Yeah, don't use the submodules. I switched to Go modules when Golan 1.11 came out.

**Comment by DataDrake** [comment]
I'll be releasing a new Cuppa in a week or two that'll get you sorted.

**Comment by maxice8** [comment]
On Mon, Dec 31, 2018 at 01:52:04PM -0800, Bryan T. Meyers wrote:
> I'll be releasing a new Cuppa in a week or two that'll get you sorted.
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/DataDrake/cli-ng/issues/1#issuecomment-450693395

Thanks for the extremely quick response

**Comment by DataDrake** [comment]
No problem :)

**Comment by alecbcs** [comment]
Have there been any updates to this issue recently? I'm interested in using cuppa as a dependency of another go program but when attempting to import it I'm getting this same error.

**Comment by DataDrake** [comment]
Shouldn't be an issue with master, are you trying to use cuppa 1.0.4?

**Comment by alecbcs** [comment]
I don't believe so? I'm attempting to import it using `go get "github.com/DataDrake/cuppa"`. Which I believe should just pull master since I haven't tagged a version. Would you recommend pulling the repository manually instead?

**Comment by DataDrake** [comment]
You really should be using Go modules, not go get on its own. Otherwise it won't pull in cuppa's deps.

**Comment by alecbcs** [comment]
Ahh alright, thank you for your help! I initialized modules in my program `go mod init mod` and it imported `cuppa` correctly!

**Comment by DataDrake** [comment]
Closing since the problem was fixed ages ago and most folks should be on a new enough version of Go for Modules to work correctly.
